[package]
edition="2021"
name="koi-bench"
version="0.1.0"

[[bin]]
name="koi-bench"
path="bin.rs"

[dependencies]
indicatif="0.17"
strum="0.26"
strum_macros="0.26"
walkdir="2.5"

koi={path="../koi"}
png="0.17.13"
qoi="0.4.1"
webp="0.3.0"
